name: brew test-bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Homebrew/actions/setup-homebrew@master

      - name: Run brew test-bot --only-tap-syntax
        run: brew test-bot --only-tap-syntax
